version: "3.9"

networks:
  smart-home-iot-network:
    external: true

services:
  frontend:
    build:
      context: ./smarthome-dashboard
      dockerfile: Dockerfile
    container_name: smart-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - smart-home-iot-network
    command: ["npm", "run", "dev"]
    restart: unless-stopped
