spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/smarthome_prod?useSSL=false&serverTimezone=Asia/Seoul
    username: prod_user
    password: prod_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: prod-redis-host
    port: 6379

  kafka:
    bootstrap-servers: prod-kafka-host:9092

server:
  port: 80

logging:
  level:
    root: info